version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fleet-manager-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: fleetmanager
      POSTGRES_PASSWORD: fleetmanager_dev
      POSTGRES_DB: fleet_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fleetmanager"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: fleet-manager-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
