name = "fleet-manager-system"
compatibility_date = "2024-01-01"

[env.production]
vars = { NODE_ENV = "production" }

[[env.production.routes]]
pattern = "www.primeofferonline.shop/*"
zone_name = "primeofferonline.shop"