name = "fleet-manager-system"
compatibility_date = "2024-01-15"
pages_build_output_dir = ".next"

[build]
command = "npm run cf-build"

[[pages.env_vars]]
name = "NODE_VERSION"
value = "18"

[env.production]
vars = { NODE_ENV = "production" }