'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'en' | 'ar'

interface LanguageContextType {
  language: Language
  toggleLanguage: () => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.trucks': 'Trucks',
    'nav.maintenance': 'Maintenance',
    'nav.mechanics': 'Mechanics',
    'nav.tireManagement': 'Tire Management',
    'nav.analytics': 'Advanced Analytics',
    'nav.reports': 'Reports',
    'nav.editor': 'Document Editor',
    'nav.users': 'Users',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.admin': 'Admin',
    'nav.logout': 'Logout',
    
    // Dashboard
    'dashboard.title': 'Fleet Maintenance Dashboard',
    'dashboard.subtitle': 'Monitor and manage your truck fleet maintenance',
    'dashboard.totalTrucks': 'Total Trucks',
    'dashboard.activeTrucks': 'active vehicles',
    'dashboard.upcomingMaintenance': 'Upcoming Maintenance',
    'dashboard.dueWithin30Days': 'Due within 30 days',
    'dashboard.overdueRepairs': 'Overdue Repairs',
    'dashboard.requireAttention': 'Require immediate attention',
    'dashboard.monthlyMaintenanceCost': 'Monthly Maintenance Cost',
    'dashboard.averageMonthlyCost': 'Average monthly cost',
    'dashboard.totalCost6mo': 'Total Cost (6mo)',
    'dashboard.last6Months': 'Last 6 months',
    'dashboard.noDataAvailable': 'No Data Available',
    'dashboard.addFirstTruck': 'Add Your First Truck',
    'dashboard.recentTrucks': 'Recent Trucks',
    'dashboard.recentMaintenance': 'Recent Maintenance',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.cost': 'Cost',
    'common.total': 'Total',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.maintenance': 'Maintenance',
    
    // Login/Auth
    'auth.login': 'Login',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.signIn': 'Sign In',
    'auth.welcome': 'Welcome Back',
    'auth.loginSubtitle': 'Sign in to your account to continue',
    
    // Trucks
    'trucks.title': 'Fleet Management',
    'trucks.subtitle': 'Manage your truck fleet',
    'trucks.addTruck': 'Add Truck',
    'trucks.vin': 'VIN',
    'trucks.make': 'Make',
    'trucks.model': 'Model',
    'trucks.year': 'Year',
    'trucks.licensePlate': 'License Plate',
    'trucks.mileage': 'Mileage',
    
    // Maintenance
    'maintenance.title': 'Maintenance Records',
    'maintenance.subtitle': 'Track and manage maintenance activities',
    'maintenance.addRecord': 'Add Maintenance Record',
    'maintenance.serviceType': 'Service Type',
    'maintenance.description': 'Description',
    'maintenance.datePerformed': 'Date Performed',
    'maintenance.partsCost': 'Parts Cost',
    'maintenance.laborCost': 'Labor Cost',
    'maintenance.totalCost': 'Total Cost',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Configure your application preferences',
    'settings.general': 'General',
    'settings.notifications': 'Notifications',
    'settings.maintenance': 'Maintenance',
    'settings.permissions': 'Permissions',
    
    // Profile
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your account information',
    'profile.name': 'Name',
    'profile.phone': 'Phone',
    'profile.department': 'Department',
    'profile.title': 'Title',
    'profile.bio': 'Bio',
    'profile.updateProfile': 'Update Profile',
    
    // Users
    'users.title': 'User Management',
    'users.subtitle': 'Manage system users and permissions',
    'users.addUser': 'Add User',
    'users.role': 'Role',
    'users.approved': 'Approved',
    'users.emailVerified': 'Email Verified',
    
    // All Pages
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'System administration and monitoring',
    'admin.activity': 'Activity Logs',
    'admin.monitoring': 'System Monitoring',
    'analytics.title': 'Advanced Analytics',
    'analytics.subtitle': 'Fleet performance insights and trends',
    'documents.title': 'Document Management',
    'documents.subtitle': 'Manage fleet documents and files',
    'editor.title': 'Document Editor',
    'editor.subtitle': 'Create and edit documents',
    'mechanics.title': 'Mechanics Management',
    'mechanics.subtitle': 'Manage mechanics and technicians',
    'tires.title': 'Tire Management',
    'tires.subtitle': 'Track tire inventory and distribution',
    'reports.title': 'Reports',
    'reports.subtitle': 'Generate fleet reports and analytics',
    'signup.title': 'Create Account',
    'signup.subtitle': 'Join the fleet management system',
    'forgotPassword.title': 'Forgot Password',
    'forgotPassword.subtitle': 'Reset your account password',
    'resetPassword.title': 'Reset Password',
    'resetPassword.subtitle': 'Enter your new password',
    'verifyEmail.title': 'Verify Email',
    'verifyEmail.subtitle': 'Confirm your email address',
    'pendingApproval.title': 'Pending Approval',
    'pendingApproval.subtitle': 'Your account is awaiting admin approval',
    
    // Form Fields
    'form.name': 'Name',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.specialty': 'Specialty',
    'form.description': 'Description',
    'form.notes': 'Notes',
    'form.required': 'Required',
    'form.optional': 'Optional',
    
    // Actions
    'action.add': 'Add',
    'action.edit': 'Edit',
    'action.delete': 'Delete',
    'action.view': 'View',
    'action.update': 'Update',
    'action.create': 'Create',
    'action.close': 'Close',
    'action.refresh': 'Refresh',
    'action.export': 'Export',
    'action.import': 'Import',
    'action.submit': 'Submit',
    'action.reset': 'Reset',
    'action.clear': 'Clear',
    
    // Status
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.pending': 'Pending',
    'status.completed': 'Completed',
    'status.inProgress': 'In Progress',
    'status.scheduled': 'Scheduled',
    'status.cancelled': 'Cancelled',
    'status.overdue': 'Overdue',
    
    // Table Headers
    'table.name': 'Name',
    'table.contact': 'Contact',
    'table.specialty': 'Specialty',
    'table.status': 'Status',
    'table.actions': 'Actions',
    'table.date': 'Date',
    'table.cost': 'Cost',
    'table.truck': 'Truck',
    'table.mechanic': 'Mechanic',
    'table.serviceType': 'Service Type',
    'table.category': 'Category',
    'table.maintenanceCount': 'Maintenance Count',
    
    // Messages
    'message.noData': 'No data found',
    'message.loading': 'Loading...',
    'message.success': 'Operation completed successfully',
    'message.error': 'An error occurred',
    'message.confirm': 'Are you sure?',
    'message.deleteConfirm': 'Are you sure you want to delete this item?',
    
    // Placeholders
    'placeholder.search': 'Search...',
    'placeholder.selectOption': 'Select an option',
    'placeholder.enterText': 'Enter text',
    'placeholder.selectDate': 'Select date',
    'placeholder.selectStatus': 'Select status',
    
    // Mechanics specific
    'mechanics.addMechanic': 'Add Mechanic',
    'mechanics.editMechanic': 'Edit Mechanic',
    'mechanics.updateMechanic': 'Update Mechanic',
    'mechanics.deleteMechanic': 'Delete Mechanic',
    'mechanics.noMechanicsFound': 'No mechanics found',
    'mechanics.searchMechanics': 'Search mechanics...',
    'mechanics.filterByStatus': 'Filter by status',
    'mechanics.allStatus': 'All Status',
    'mechanics.mechanicDetails': 'Enter the mechanic details to add them to the system',
    'mechanics.updateDetails': 'Update the mechanic information below',
    
    // Dashboard specific
    'dashboard.totalTrucks': 'Total Trucks',
    'dashboard.activeTrucks': 'active vehicles',
    'dashboard.upcomingMaintenance': 'Upcoming Maintenance',
    'dashboard.dueWithin30Days': 'Due within 30 days',
    'dashboard.overdueRepairs': 'Overdue Repairs',
    'dashboard.requireAttention': 'Require immediate attention',
    'dashboard.monthlyMaintenanceCost': 'Monthly Maintenance Cost',
    'dashboard.averageMonthlyCost': 'Average monthly cost',
    'dashboard.totalCost6mo': 'Total Cost (6mo)',
    'dashboard.last6Months': 'Last 6 months',
    'dashboard.noDataAvailable': 'No Data Available',
    'dashboard.addFirstTruck': 'Add Your First Truck',
    'dashboard.recentTrucks': 'Recent Trucks',
    'dashboard.recentMaintenance': 'Recent Maintenance',
    'dashboard.monthlyMaintenanceCosts': 'Monthly Maintenance Costs',
    'dashboard.costTrends': 'Cost trends over the last 6 months',
    'dashboard.maintenanceTypes': 'Maintenance Types',
    'dashboard.serviceDistribution': 'Distribution of service types',
    'dashboard.recentlyAddedTrucks': 'Recently Added Trucks',
    'dashboard.latestAdditions': 'Latest additions to your fleet',
    'dashboard.recentMaintenanceRecords': 'Recent Maintenance Records',
    'dashboard.latestServiceActivities': 'Latest service activities',
    'dashboard.noTrucksFound': 'No trucks found',
    'dashboard.noMaintenanceFound': 'No maintenance records found',
    
    // Maintenance specific
    'maintenance.addMaintenance': 'Add Maintenance',
    'maintenance.editMaintenance': 'Edit Maintenance Record',
    'maintenance.updateMaintenance': 'Update Record',
    'maintenance.addRecord': 'Add Record',
    'maintenance.maintenanceRecords': 'Maintenance Records',
    'maintenance.showingRecords': 'Showing {count} maintenance records',
    'maintenance.truck': 'Truck',
    'maintenance.selectTruck': 'Select truck',
    'maintenance.serviceType': 'Service Type',
    'maintenance.selectJob': 'Select predefined job (optional)',
    'maintenance.customServiceType': 'Or enter custom service type',
    'maintenance.oilChangeService': 'Oil Change Service',
    'maintenance.isOilChange': 'This is an oil change service',
    'maintenance.oilChangeInterval': 'Oil Change Interval (km)',
    'maintenance.currentMileage': 'Current Mileage (km)',
    'maintenance.datePerformed': 'Date Performed',
    'maintenance.mechanic': 'Mechanic',
    'maintenance.selectMechanic': 'Select mechanic (optional)',
    'maintenance.noMechanic': 'No Mechanic',
    'maintenance.partsCost': 'Parts Cost',
    'maintenance.laborCost': 'Labor Cost',
    'maintenance.nextServiceDue': 'Next Service Due',
    'maintenance.maintenanceDetails': 'Maintenance Record Details',
    'maintenance.completeInformation': 'View the complete maintenance record information',
    'maintenance.created': 'Created',
    'maintenance.lastUpdated': 'Last Updated',
    'maintenance.oilChange': 'Oil Change',
    'maintenance.nextService': 'Next',
    
    // Trucks specific
    'trucks.addTruck': 'Add Truck',
    'trucks.editTruck': 'Edit Truck',
    'trucks.updateTruck': 'Update Truck',
    'trucks.deleteTruck': 'Delete Truck',
    'trucks.truckDetails': 'Truck Details',
    'trucks.fleetOverview': 'Fleet Overview',
    'trucks.showingTrucks': 'Showing {count} trucks',
    'trucks.vin': 'VIN',
    'trucks.make': 'Make',
    'trucks.model': 'Model',
    'trucks.year': 'Year',
    'trucks.licensePlate': 'License Plate',
    'trucks.mileage': 'Mileage',
    'trucks.currentMileage': 'Current Mileage',
    'trucks.vehicle': 'Vehicle',
    'trucks.added': 'Added',
    'trucks.miles': 'miles',
    'trucks.documents': 'Documents',
    'trucks.documentsAttached': '{count} document(s) attached',
    'trucks.noDocuments': 'No documents attached',
    'trucks.manageFiles': 'Manage Files',
    'trucks.uploadDocuments': 'Upload and manage documents for this truck',
    'trucks.done': 'Done',
    
    // Analytics specific
    'analytics.fleetUptime': 'Fleet Uptime',
    'analytics.maintenanceCosts': 'Maintenance Costs',
    'analytics.mechanicEfficiency': 'Mechanic Efficiency',
    'analytics.lastMonth': 'Last Month',
    'analytics.last3Months': 'Last 3 Months',
    'analytics.last6Months': 'Last 6 Months',
    'analytics.lastYear': 'Last Year',
    'analytics.allTrucks': 'All Trucks',
    'analytics.selectPeriod': 'Select period',
    'analytics.maintenanceTrends': 'Maintenance Trends',
    'analytics.activitiesOverTime': 'Maintenance activities over time',
    'analytics.costAnalysis': 'Cost Analysis',
    'analytics.costBreakdown': 'Breakdown of maintenance costs',
    'analytics.truckPerformance': 'Truck Performance',
    'analytics.performanceIndicators': 'Key performance indicators for each truck',
    'analytics.mechanicProductivity': 'Mechanic Productivity',
    'analytics.performanceMetrics': 'Performance metrics for maintenance staff',
    'analytics.scheduled': 'Scheduled',
    'analytics.completed': 'Completed',
    'analytics.inProgress': 'In Progress',
    'analytics.overdue': 'Overdue',
    'analytics.uptime': 'Uptime %',
    'analytics.maintenanceCost': 'Maintenance Cost $',
    'analytics.completedJobs': 'Completed Jobs',
    'analytics.efficiency': 'Efficiency %',
    'analytics.improvement': 'improvement',
    'analytics.fromLastMonth': 'from last month',
    'analytics.noDataAvailable': 'No data available',
    
    // Trucks specific
    'trucks.updateDetails': 'Update the truck information below',
    'trucks.truckDetails': 'Enter the details for the new truck',
    'trucks.viewDetailedInformation': 'View detailed information about this truck',
    'trucks.enterUniqueVin': 'Enter unique VIN',
    'trucks.enterUniqueLicensePlate': 'Enter unique license plate',
    'trucks.vinMustBeUnique': 'Vehicle Identification Number must be unique',
    'trucks.licensePlateMustBeUnique': 'License plate must be unique',
    'trucks.vinAlreadyExists': 'This VIN already exists',
    'trucks.licensePlateAlreadyExists': 'This license plate already exists',
    
    // Messages
    'message.accessDenied': 'Access Denied',
    'message.noPermission': 'You don\'t have permission to access this feature',
    'message.fixErrors': 'Please fix the following errors:',
    'message.fillRequiredFields': 'Please fill in all required fields',
    'message.fixValidationErrors': 'Please fix validation errors before submitting',
    
    // Complete website translations
    'analytics.refresh': 'Refresh',
    'analytics.export': 'Export',
    'analytics.selectPeriod': 'Select period',
    'analytics.allTrucks': 'All Trucks',
    'analytics.parts': 'Parts',
    'analytics.labor': 'Labor',
    'analytics.externalServices': 'External Services',
    'analytics.other': 'Other',
    'analytics.legend': 'Legend',
    
    // Tire Management
    'tires.addTires': 'Add Tires',
    'tires.inventory': 'Inventory',
    'tires.vehicles': 'Vehicles',
    'tires.analytics': 'Analytics',
    'tires.reports': 'Reports',
    'tires.tireSize': 'Tire Size',
    'tires.manufacturer': 'Manufacturer',
    'tires.origin': 'Origin',
    'tires.plateNumber': 'Plate Number',
    'tires.trailerNumber': 'Trailer Number',
    'tires.driverName': 'Driver Name',
    'tires.quantity': 'Quantity',
    'tires.chinese': 'Chinese',
    'tires.japanese': 'Japanese',
    'tires.european': 'European',
    'tires.american': 'American',
    'tires.other': 'Other',
    
    // Users
    'users.addUser': 'Add User',
    'users.editUser': 'Edit User',
    'users.deleteUser': 'Delete User',
    'users.userDetails': 'User Details',
    'users.permissions': 'Permissions',
    'users.lastLogin': 'Last Login',
    'users.createdAt': 'Created At',
    'users.admin': 'Admin',
    'users.manager': 'Manager',
    'users.user': 'User',
    
    // Profile
    'profile.updateProfile': 'Update Profile',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm Password',
    'profile.profileImage': 'Profile Image',
    'profile.personalInformation': 'Personal Information',
    'profile.contactInformation': 'Contact Information',
    
    // Settings
    'settings.general': 'General',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language',
    'settings.currency': 'Currency',
    'settings.timezone': 'Timezone',
    'settings.emailNotifications': 'Email Notifications',
    'settings.pushNotifications': 'Push Notifications',
    'settings.maintenanceAlerts': 'Maintenance Alerts',
    
    // Reports
    'reports.generateReport': 'Generate Report',
    'reports.reportType': 'Report Type',
    'reports.dateRange': 'Date Range',
    'reports.startDate': 'Start Date',
    'reports.endDate': 'End Date',
    'reports.format': 'Format',
    'reports.pdf': 'PDF',
    'reports.excel': 'Excel',
    'reports.csv': 'CSV',
    'reports.download': 'Download',
    'reports.preview': 'Preview',
    
    // Documents
    'documents.uploadDocument': 'Upload Document',
    'documents.documentName': 'Document Name',
    'documents.documentType': 'Document Type',
    'documents.fileSize': 'File Size',
    'documents.uploadDate': 'Upload Date',
    'documents.downloadDocument': 'Download Document',
    'documents.deleteDocument': 'Delete Document',
    
    // Editor
    'editor.newDocument': 'New Document',
    'editor.saveDocument': 'Save Document',
    'editor.documentTitle': 'Document Title',
    'editor.content': 'Content',
    'editor.formatting': 'Formatting',
    'editor.bold': 'Bold',
    'editor.italic': 'Italic',
    'editor.underline': 'Underline',
    
    // Admin
    'admin.systemHealth': 'System Health',
    'admin.userActivity': 'User Activity',
    'admin.systemLogs': 'System Logs',
    'admin.databaseStatus': 'Database Status',
    'admin.serverStatus': 'Server Status',
    'admin.backupStatus': 'Backup Status',
    'admin.lastBackup': 'Last Backup',
    'admin.nextBackup': 'Next Backup',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.trucks': 'Trucks',
    'nav.maintenance': 'Maintenance',
    'nav.mechanics': 'Mechanics',
    'nav.tires': 'Tire Management',
    'nav.analytics': 'Analytics',
    'nav.reports': 'Reports',
    'nav.documents': 'Documents',
    'nav.users': 'Users',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',
    'nav.logout': 'Logout',
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.trucks': 'الشاحنات',
    'nav.maintenance': 'الصيانة',
    'nav.mechanics': 'الميكانيكيين',
    'nav.tireManagement': 'إدارة الإطارات',
    'nav.analytics': 'التحليلات المتقدمة',
    'nav.reports': 'التقارير',
    'nav.editor': 'محرر المستندات',
    'nav.users': 'المستخدمين',
    'nav.profile': 'الملف الشخصي',
    'nav.settings': 'الإعدادات',
    'nav.admin': 'المدير',
    'nav.logout': 'تسجيل الخروج',
    
    // Dashboard
    'dashboard.title': 'لوحة تحكم صيانة الأسطول',
    'dashboard.subtitle': 'راقب وأدر صيانة أسطول الشاحنات الخاص بك',
    'dashboard.totalTrucks': 'إجمالي الشاحنات',
    'dashboard.activeTrucks': 'مركبات نشطة',
    'dashboard.upcomingMaintenance': 'الصيانة القادمة',
    'dashboard.dueWithin30Days': 'مستحقة خلال 30 يوماً',
    'dashboard.overdueRepairs': 'الإصلاحات المتأخرة',
    'dashboard.requireAttention': 'تتطلب اهتماماً فورياً',
    'dashboard.monthlyMaintenanceCost': 'تكلفة الصيانة الشهرية',
    'dashboard.averageMonthlyCost': 'متوسط التكلفة الشهرية',
    'dashboard.totalCost6mo': 'التكلفة الإجمالية (6 أشهر)',
    'dashboard.last6Months': 'آخر 6 أشهر',
    'dashboard.noDataAvailable': 'لا توجد بيانات متاحة',
    'dashboard.addFirstTruck': 'أضف شاحنتك الأولى',
    'dashboard.recentTrucks': 'الشاحنات الحديثة',
    'dashboard.recentMaintenance': 'الصيانة الحديثة',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.add': 'إضافة',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.status': 'الحالة',
    'common.date': 'التاريخ',
    'common.cost': 'التكلفة',
    'common.total': 'المجموع',
    'common.active': 'نشط',
    'common.inactive': 'غير نشط',
    'common.maintenance': 'صيانة',
    
    // Login/Auth
    'auth.login': 'تسجيل الدخول',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.signIn': 'تسجيل الدخول',
    'auth.welcome': 'مرحباً بعودتك',
    'auth.loginSubtitle': 'سجل دخولك إلى حسابك للمتابعة',
    
    // Trucks
    'trucks.title': 'إدارة الأسطول',
    'trucks.subtitle': 'إدارة أسطول الشاحنات الخاص بك',
    'trucks.addTruck': 'إضافة شاحنة',
    'trucks.vin': 'رقم الهيكل',
    'trucks.make': 'الصانع',
    'trucks.model': 'الطراز',
    'trucks.year': 'السنة',
    'trucks.licensePlate': 'رقم اللوحة',
    'trucks.mileage': 'المسافة المقطوعة',
    
    // Maintenance
    'maintenance.title': 'سجلات الصيانة',
    'maintenance.subtitle': 'تتبع وإدارة أنشطة الصيانة',
    'maintenance.addRecord': 'إضافة سجل صيانة',
    'maintenance.serviceType': 'نوع الخدمة',
    'maintenance.description': 'الوصف',
    'maintenance.datePerformed': 'تاريخ التنفيذ',
    'maintenance.partsCost': 'تكلفة القطع',
    'maintenance.laborCost': 'تكلفة العمالة',
    'maintenance.totalCost': 'التكلفة الإجمالية',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.subtitle': 'تكوين تفضيلات التطبيق الخاص بك',
    'settings.general': 'عام',
    'settings.notifications': 'الإشعارات',
    'settings.maintenance': 'الصيانة',
    'settings.permissions': 'الصلاحيات',
    
    // Profile
    'profile.title': 'الملف الشخصي',
    'profile.subtitle': 'إدارة معلومات حسابك',
    'profile.name': 'الاسم',
    'profile.phone': 'الهاتف',
    'profile.department': 'القسم',
    'profile.title': 'المسمى الوظيفي',
    'profile.bio': 'النبذة الشخصية',
    'profile.updateProfile': 'تحديث الملف الشخصي',
    
    // Users
    'users.title': 'إدارة المستخدمين',
    'users.subtitle': 'إدارة مستخدمي النظام والصلاحيات',
    'users.addUser': 'إضافة مستخدم',
    'users.role': 'الدور',
    'users.approved': 'موافق عليه',
    'users.emailVerified': 'البريد الإلكتروني مُتحقق منه',
    
    // All Pages
    'admin.title': 'لوحة تحكم المدير',
    'admin.subtitle': 'إدارة النظام والمراقبة',
    'admin.activity': 'سجلات النشاط',
    'admin.monitoring': 'مراقبة النظام',
    'analytics.title': 'التحليلات المتقدمة',
    'analytics.subtitle': 'رؤى أداء الأسطول والاتجاهات',
    'documents.title': 'إدارة المستندات',
    'documents.subtitle': 'إدارة مستندات وملفات الأسطول',
    'editor.title': 'محرر المستندات',
    'editor.subtitle': 'إنشاء وتحرير المستندات',
    'mechanics.title': 'إدارة الميكانيكيين',
    'mechanics.subtitle': 'إدارة الميكانيكيين والفنيين',
    'tires.title': 'إدارة الإطارات',
    'tires.subtitle': 'تتبع مخزون الإطارات والتوزيع',
    'reports.title': 'التقارير',
    'reports.subtitle': 'إنشاء تقارير الأسطول والتحليلات',
    'signup.title': 'إنشاء حساب',
    'signup.subtitle': 'انضم إلى نظام إدارة الأسطول',
    'forgotPassword.title': 'نسيت كلمة المرور',
    'forgotPassword.subtitle': 'إعادة تعيين كلمة مرور حسابك',
    'resetPassword.title': 'إعادة تعيين كلمة المرور',
    'resetPassword.subtitle': 'أدخل كلمة المرور الجديدة',
    'verifyEmail.title': 'تحقق من البريد الإلكتروني',
    'verifyEmail.subtitle': 'تأكيد عنوان بريدك الإلكتروني',
    'pendingApproval.title': 'في انتظار الموافقة',
    'pendingApproval.subtitle': 'حسابك في انتظار موافقة المدير',
    
    // Form Fields
    'form.name': 'الاسم',
    'form.email': 'البريد الإلكتروني',
    'form.phone': 'الهاتف',
    'form.specialty': 'التخصص',
    'form.description': 'الوصف',
    'form.notes': 'الملاحظات',
    'form.required': 'مطلوب',
    'form.optional': 'اختياري',
    
    // Actions
    'action.add': 'إضافة',
    'action.edit': 'تعديل',
    'action.delete': 'حذف',
    'action.view': 'عرض',
    'action.update': 'تحديث',
    'action.create': 'إنشاء',
    'action.close': 'إغلاق',
    'action.refresh': 'تحديث',
    'action.export': 'تصدير',
    'action.import': 'استيراد',
    'action.submit': 'إرسال',
    'action.reset': 'إعادة تعيين',
    'action.clear': 'مسح',
    
    // Status
    'status.active': 'نشط',
    'status.inactive': 'غير نشط',
    'status.pending': 'في الانتظار',
    'status.completed': 'مكتمل',
    'status.inProgress': 'قيد التنفيذ',
    'status.scheduled': 'مجدول',
    'status.cancelled': 'ملغي',
    'status.overdue': 'متأخر',
    
    // Table Headers
    'table.name': 'الاسم',
    'table.contact': 'جهة الاتصال',
    'table.specialty': 'التخصص',
    'table.status': 'الحالة',
    'table.actions': 'الإجراءات',
    'table.date': 'التاريخ',
    'table.cost': 'التكلفة',
    'table.truck': 'الشاحنة',
    'table.mechanic': 'الميكانيكي',
    'table.serviceType': 'نوع الخدمة',
    'table.category': 'الفئة',
    'table.maintenanceCount': 'عدد الصيانات',
    
    // Messages
    'message.noData': 'لا توجد بيانات',
    'message.loading': 'جاري التحميل...',
    'message.success': 'تمت العملية بنجاح',
    'message.error': 'حدث خطأ',
    'message.confirm': 'هل أنت متأكد؟',
    'message.deleteConfirm': 'هل أنت متأكد من حذف هذا العنصر؟',
    
    // Placeholders
    'placeholder.search': 'بحث...',
    'placeholder.selectOption': 'اختر خياراً',
    'placeholder.enterText': 'أدخل النص',
    'placeholder.selectDate': 'اختر التاريخ',
    'placeholder.selectStatus': 'اختر الحالة',
    
    // Mechanics specific
    'mechanics.addMechanic': 'إضافة ميكانيكي',
    'mechanics.editMechanic': 'تعديل ميكانيكي',
    'mechanics.updateMechanic': 'تحديث ميكانيكي',
    'mechanics.deleteMechanic': 'حذف ميكانيكي',
    'mechanics.noMechanicsFound': 'لم يتم العثور على ميكانيكيين',
    'mechanics.searchMechanics': 'بحث عن ميكانيكيين...',
    'mechanics.filterByStatus': 'تصفية حسب الحالة',
    'mechanics.allStatus': 'جميع الحالات',
    'mechanics.mechanicDetails': 'أدخل تفاصيل الميكانيكي لإضافته إلى النظام',
    'maintenance.mechanicDetails': 'أدخل تفاصيل سجل الصيانة الجديد',
    'mechanics.updateDetails': 'حدث معلومات الميكانيكي أدناه',
    'maintenance.updateDetails': 'حدث معلومات سجل الصيانة أدناه',
    
    // Dashboard specific
    'dashboard.totalTrucks': 'إجمالي الشاحنات',
    'dashboard.activeTrucks': 'مركبات نشطة',
    'dashboard.upcomingMaintenance': 'الصيانة القادمة',
    'dashboard.dueWithin30Days': 'مستحقة خلال 30 يوماً',
    'dashboard.overdueRepairs': 'الإصلاحات المتأخرة',
    'dashboard.requireAttention': 'تتطلب اهتماماً فورياً',
    'dashboard.monthlyMaintenanceCost': 'تكلفة الصيانة الشهرية',
    'dashboard.averageMonthlyCost': 'متوسط التكلفة الشهرية',
    'dashboard.totalCost6mo': 'التكلفة الإجمالية (6 أشهر)',
    'dashboard.last6Months': 'آخر 6 أشهر',
    'dashboard.noDataAvailable': 'لا توجد بيانات متاحة',
    'dashboard.addFirstTruck': 'أضف شاحنتك الأولى',
    'dashboard.recentTrucks': 'الشاحنات الحديثة',
    'dashboard.recentMaintenance': 'الصيانة الحديثة',
    'dashboard.monthlyMaintenanceCosts': 'تكاليف الصيانة الشهرية',
    'dashboard.costTrends': 'اتجاهات التكلفة خلال آخر 6 أشهر',
    'dashboard.maintenanceTypes': 'أنواع الصيانة',
    'dashboard.serviceDistribution': 'توزيع أنواع الخدمات',
    'dashboard.recentlyAddedTrucks': 'الشاحنات المضافة حديثاً',
    'dashboard.latestAdditions': 'آخر الإضافات إلى أسطولك',
    'dashboard.recentMaintenanceRecords': 'سجلات الصيانة الحديثة',
    'dashboard.latestServiceActivities': 'آخر أنشطة الخدمة',
    'dashboard.noTrucksFound': 'لم يتم العثور على شاحنات',
    'dashboard.noMaintenanceFound': 'لم يتم العثور على سجلات صيانة',
    
    // Maintenance specific
    'maintenance.addMaintenance': 'إضافة صيانة',
    'maintenance.editMaintenance': 'تعديل سجل الصيانة',
    'maintenance.updateMaintenance': 'تحديث السجل',
    'maintenance.addRecord': 'إضافة سجل',
    'maintenance.maintenanceRecords': 'سجلات الصيانة',
    'maintenance.showingRecords': 'عرض {count} سجل صيانة',
    'maintenance.truck': 'الشاحنة',
    'maintenance.selectTruck': 'اختر شاحنة',
    'maintenance.serviceType': 'نوع الخدمة',
    'maintenance.selectJob': 'اختر عمل محدد مسبقاً (اختياري)',
    'maintenance.customServiceType': 'أو أدخل نوع خدمة مخصص',
    'maintenance.oilChangeService': 'خدمة تغيير الزيت',
    'maintenance.isOilChange': 'هذه خدمة تغيير زيت',
    'maintenance.oilChangeInterval': 'فترة تغيير الزيت (كم)',
    'maintenance.currentMileage': 'المسافة الحالية (كم)',
    'maintenance.datePerformed': 'تاريخ التنفيذ',
    'maintenance.mechanic': 'الميكانيكي',
    'maintenance.selectMechanic': 'اختر ميكانيكي (اختياري)',
    'maintenance.noMechanic': 'لا يوجد ميكانيكي',
    'maintenance.partsCost': 'تكلفة القطع',
    'maintenance.laborCost': 'تكلفة العمالة',
    'maintenance.nextServiceDue': 'الخدمة التالية مستحقة',
    'maintenance.maintenanceDetails': 'تفاصيل سجل الصيانة',
    'maintenance.completeInformation': 'عرض معلومات سجل الصيانة الكاملة',
    'maintenance.created': 'تم إنشاؤه',
    'maintenance.lastUpdated': 'آخر تحديث',
    'maintenance.oilChange': 'تغيير زيت',
    'maintenance.nextService': 'التالي',
    
    // Trucks specific
    'trucks.addTruck': 'إضافة شاحنة',
    'trucks.editTruck': 'تعديل شاحنة',
    'trucks.updateTruck': 'تحديث شاحنة',
    'trucks.deleteTruck': 'حذف شاحنة',
    'trucks.truckDetails': 'تفاصيل الشاحنة',
    'trucks.fleetOverview': 'نظرة عامة على الأسطول',
    'trucks.showingTrucks': 'عرض {count} شاحنة',
    'trucks.vin': 'رقم الهيكل',
    'trucks.make': 'الصانع',
    'trucks.model': 'الطراز',
    'trucks.year': 'السنة',
    'trucks.licensePlate': 'رقم اللوحة',
    'trucks.mileage': 'المسافة المقطوعة',
    'trucks.currentMileage': 'المسافة الحالية',
    'trucks.vehicle': 'المركبة',
    'trucks.added': 'مُضاف',
    'trucks.miles': 'ميل',
    'trucks.documents': 'المستندات',
    'trucks.documentsAttached': '{count} مستند مرفق',
    'trucks.noDocuments': 'لا توجد مستندات مرفقة',
    'trucks.manageFiles': 'إدارة الملفات',
    'trucks.uploadDocuments': 'رفع وإدارة مستندات هذه الشاحنة',
    'trucks.done': 'تم',
    
    // Analytics specific
    'analytics.fleetUptime': 'وقت تشغيل الأسطول',
    'analytics.maintenanceCosts': 'تكاليف الصيانة',
    'analytics.mechanicEfficiency': 'كفاءة الميكانيكي',
    'analytics.lastMonth': 'الشهر الماضي',
    'analytics.last3Months': 'آخر 3 أشهر',
    'analytics.last6Months': 'آخر 6 أشهر',
    'analytics.lastYear': 'العام الماضي',
    'analytics.allTrucks': 'جميع الشاحنات',
    'analytics.selectPeriod': 'اختر الفترة',
    'analytics.maintenanceTrends': 'اتجاهات الصيانة',
    'analytics.activitiesOverTime': 'أنشطة الصيانة عبر الوقت',
    'analytics.costAnalysis': 'تحليل التكاليف',
    'analytics.costBreakdown': 'تفصيل تكاليف الصيانة',
    'analytics.truckPerformance': 'أداء الشاحنات',
    'analytics.performanceIndicators': 'مؤشرات الأداء الرئيسية لكل شاحنة',
    'analytics.mechanicProductivity': 'إنتاجية الميكانيكي',
    'analytics.performanceMetrics': 'مقاييس الأداء لموظفي الصيانة',
    'analytics.scheduled': 'مجدول',
    'analytics.completed': 'مكتمل',
    'analytics.inProgress': 'قيد التنفيذ',
    'analytics.overdue': 'متأخر',
    'analytics.uptime': 'وقت التشغيل %',
    'analytics.maintenanceCost': 'تكلفة الصيانة $',
    'analytics.completedJobs': 'المهام المكتملة',
    'analytics.efficiency': 'الكفاءة %',
    'analytics.improvement': 'تحسن',
    'analytics.fromLastMonth': 'من الشهر الماضي',
    'analytics.noDataAvailable': 'لا توجد بيانات متاحة',
    
    // Trucks specific
    'trucks.updateDetails': 'حدث معلومات الشاحنة أدناه',
    'trucks.truckDetails': 'أدخل تفاصيل الشاحنة الجديدة',
    'trucks.viewDetailedInformation': 'عرض معلومات تفصيلية عن هذه الشاحنة',
    'trucks.enterUniqueVin': 'أدخل رقم هيكل فريد',
    'trucks.enterUniqueLicensePlate': 'أدخل رقم لوحة فريد',
    'trucks.vinMustBeUnique': 'رقم تعريف المركبة يجب أن يكون فريداً',
    'trucks.licensePlateMustBeUnique': 'رقم اللوحة يجب أن يكون فريداً',
    'trucks.vinAlreadyExists': 'رقم الهيكل هذا موجود بالفعل',
    'trucks.licensePlateAlreadyExists': 'رقم اللوحة هذا موجود بالفعل',
    
    // Messages
    'message.accessDenied': 'تم رفض الوصول',
    'message.noPermission': 'ليس لديك إذن للوصول إلى هذه الميزة',
    'message.fixErrors': 'يرجى إصلاح الأخطاء التالية:',
    'message.fillRequiredFields': 'يرجى ملء جميع الحقول المطلوبة',
    'message.fixValidationErrors': 'يرجى إصلاح أخطاء التحقق قبل الإرسال',
    
    // Complete website translations
    'analytics.refresh': 'تحديث',
    'analytics.export': 'تصدير',
    'analytics.selectPeriod': 'اختر الفترة',
    'analytics.allTrucks': 'جميع الشاحنات',
    'analytics.parts': 'قطع غيار',
    'analytics.labor': 'عمالة',
    'analytics.externalServices': 'خدمات خارجية',
    'analytics.other': 'أخرى',
    'analytics.legend': 'المفتاح',
    
    // Tire Management
    'tires.addTires': 'إضافة إطارات',
    'tires.inventory': 'المخزون',
    'tires.vehicles': 'المركبات',
    'tires.analytics': 'التحليلات',
    'tires.reports': 'التقارير',
    'tires.tireSize': 'حجم الإطار',
    'tires.manufacturer': 'الشركة المصنعة',
    'tires.origin': 'المنشأ',
    'tires.plateNumber': 'رقم اللوحة',
    'tires.trailerNumber': 'رقم المقطورة',
    'tires.driverName': 'اسم السائق',
    'tires.quantity': 'الكمية',
    'tires.chinese': 'صيني',
    'tires.japanese': 'ياباني',
    'tires.european': 'أوروبي',
    'tires.american': 'أمريكي',
    'tires.other': 'أخرى',
    
    // Users
    'users.addUser': 'إضافة مستخدم',
    'users.editUser': 'تعديل مستخدم',
    'users.deleteUser': 'حذف مستخدم',
    'users.userDetails': 'تفاصيل المستخدم',
    'users.permissions': 'الصلاحيات',
    'users.lastLogin': 'آخر تسجيل دخول',
    'users.createdAt': 'تاريخ الإنشاء',
    'users.admin': 'مدير',
    'users.manager': 'مدير قسم',
    'users.user': 'مستخدم',
    
    // Profile
    'profile.updateProfile': 'تحديث الملف الشخصي',
    'profile.changePassword': 'تغيير كلمة المرور',
    'profile.currentPassword': 'كلمة المرور الحالية',
    'profile.newPassword': 'كلمة المرور الجديدة',
    'profile.confirmPassword': 'تأكيد كلمة المرور',
    'profile.profileImage': 'صورة الملف الشخصي',
    'profile.personalInformation': 'المعلومات الشخصية',
    'profile.contactInformation': 'معلومات الاتصال',
    
    // Settings
    'settings.general': 'عام',
    'settings.notifications': 'الإشعارات',
    'settings.security': 'الأمان',
    'settings.appearance': 'المظهر',
    'settings.language': 'اللغة',
    'settings.currency': 'العملة',
    'settings.timezone': 'المنطقة الزمنية',
    'settings.emailNotifications': 'إشعارات البريد الإلكتروني',
    'settings.pushNotifications': 'الإشعارات الفورية',
    'settings.maintenanceAlerts': 'تنبيهات الصيانة',
    
    // Reports
    'reports.generateReport': 'إنشاء تقرير',
    'reports.reportType': 'نوع التقرير',
    'reports.dateRange': 'نطاق التاريخ',
    'reports.startDate': 'تاريخ البداية',
    'reports.endDate': 'تاريخ النهاية',
    'reports.format': 'التنسيق',
    'reports.pdf': 'PDF',
    'reports.excel': 'Excel',
    'reports.csv': 'CSV',
    'reports.download': 'تحميل',
    'reports.preview': 'معاينة',
    
    // Documents
    'documents.uploadDocument': 'رفع مستند',
    'documents.documentName': 'اسم المستند',
    'documents.documentType': 'نوع المستند',
    'documents.fileSize': 'حجم الملف',
    'documents.uploadDate': 'تاريخ الرفع',
    'documents.downloadDocument': 'تحميل المستند',
    'documents.deleteDocument': 'حذف المستند',
    
    // Editor
    'editor.newDocument': 'مستند جديد',
    'editor.saveDocument': 'حفظ المستند',
    'editor.documentTitle': 'عنوان المستند',
    'editor.content': 'المحتوى',
    'editor.formatting': 'التنسيق',
    'editor.bold': 'عريض',
    'editor.italic': 'مائل',
    'editor.underline': 'تحته خط',
    
    // Admin
    'admin.systemHealth': 'صحة النظام',
    'admin.userActivity': 'نشاط المستخدمين',
    'admin.systemLogs': 'سجلات النظام',
    'admin.databaseStatus': 'حالة قاعدة البيانات',
    'admin.serverStatus': 'حالة الخادم',
    'admin.backupStatus': 'حالة النسخ الاحتياطي',
    'admin.lastBackup': 'آخر نسخة احتياطية',
    'admin.nextBackup': 'النسخة الاحتياطية التالية',
    
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.trucks': 'الشاحنات',
    'nav.maintenance': 'الصيانة',
    'nav.mechanics': 'الميكانيكيين',
    'nav.tires': 'إدارة الإطارات',
    'nav.analytics': 'التحليلات',
    'nav.reports': 'التقارير',
    'nav.documents': 'المستندات',
    'nav.users': 'المستخدمين',
    'nav.settings': 'الإعدادات',
    'nav.profile': 'الملف الشخصي',
    'nav.admin': 'الإدارة',
    'nav.logout': 'تسجيل الخروج',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ar')) {
      setLanguage(savedLanguage)
      document.documentElement.lang = savedLanguage
      document.documentElement.dir = savedLanguage === 'ar' ? 'rtl' : 'ltr'
    }
  }, [])

  const toggleLanguage = () => {
    const newLanguage = language === 'en' ? 'ar' : 'en'
    setLanguage(newLanguage)
    localStorage.setItem('language', newLanguage)
    document.documentElement.lang = newLanguage
    document.documentElement.dir = newLanguage === 'ar' ? 'rtl' : 'ltr'
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}